#!/usr/bin/env bash

#
# Will create a build copying files

# Import javascript files that are present in index.html
mkdir -p dist/

#PrimeNG/PrimeUI CSS dependencies
mkdir -p dist/node_modules/primeui/themes/omega/ && cp -a node_modules/primeui/themes/omega/ "$_"
mkdir -p dist/assets/ && cp -a assets/ "$_"
mkdir -p dist/node_modules/primeui/ && cp node_modules/primeui/primeui-ng-all.min.css "$_"

#Load Angular libraries
mkdir -p dist/node_modules/es6-shim/ && cp node_modules/es6-shim/es6-shim.min.js "$_"
mkdir -p dist/node_modules/zone.js/dist/ && cp node_modules/zone.js/dist/zone.js "$_"
mkdir -p dist/node_modules/reflect-metadata/ && cp node_modules/reflect-metadata/Reflect.js "$_"
mkdir -p dist/node_modules/systemjs/dist/ && cp node_modules/systemjs/dist/system.src.js "$_"
mkdir -p dist/node_modules/primeui/ && cp node_modules/primeui/primeui-ng-all.js "$_"
cp systemjs.config.js dist/systemjs.config.js

#<!--CodeMirror setup-->
mkdir -p dist/assets/css/ && cp assets/css/codemirror.css "$_"
mkdir -p dist/node_modules/codemirror/lib/ && cp node_modules/codemirror/lib/codemirror.js "$_"
mkdir -p dist/node_modules/codemirror/mode/clike/ && cp node_modules/codemirror/mode/clike/clike.js "$_"


#Import javascript files