import {NgModule} from "@angular/core";
import {BrowserModule} from "@angular/platform-browser";
import {
    InputTextModule,
    TreeTableModule,
    TreeModule,
    TooltipModule,
    ToolbarModule,
    ToggleButtonModule,
    TieredMenuModule,
    TerminalModule,
    TabViewModule,
    TabMenuModule,
    SplitButtonModule,
    SpinnerModule,
    SliderModule,
    SlideMenuModule,
    SelectButtonModule,
    ScheduleModule,
    RatingModule,
    RadioButtonModule,
    ProgressBarModule,
    PickListModule,
    PasswordModule,
    PanelMenuModule,
    PanelModule,
    PaginatorModule,
    OverlayPanelModule,
    OrderListModule,
    MultiSelectModule,
    MessagesModule,
    MenubarModule,
    MenuModule,
    MegaMenuModule,
    ListboxModule,
    LightboxModule,
    InputTextareaModule,
    InputSwitchModule,
    AccordionModule,
    AutoCompleteModule,
    BreadcrumbModule,
    ButtonModule,
    CalendarModule,
    CarouselModule,
    ChartModule,
    CheckboxModule,
    CodeHighlighterModule,
    SharedModule,
    ContextMenuModule,
    DataGridModule,
    DataListModule,
    DataScrollerModule,
    DataTableModule,
    DialogModule,
    DragDropModule,
    DropdownModule,
    EditorModule,
    FieldsetModule,
    GalleriaModule,
    GMapModule,
    GrowlModule,
    InputMaskModule
} from "primeng/primeng";
import {HttpModule} from "@angular/http";
import {FormsModule, ReactiveFormsModule} from "@angular/forms";
import {MainComponent} from "./main.component";
import {AppComponent} from "./app/app.component";
import {JavalabService} from "./services/javalab.service";
import {TagService} from "./services/tag.service";
import {routing, routingProviders} from "./main.routes";
import {DescriptionComponent} from "./description/description.component";
import {FileManagerComponent} from "./filemanager/filemanager.component";
import {CodeMirrorComponent} from "./codemirror/codemirror.component";
import {TagsComponent} from "./tags/tags.component";
import {NavBarComponent} from "./nav-bar/navbar.component";
import {TerminalComponent} from "./terminal/terminal.component";

@NgModule({
    imports: [
        routing,
        BrowserModule,
        InputTextModule,
        BrowserModule,
        FormsModule,
        ReactiveFormsModule,
        HttpModule,
        AccordionModule,
        AutoCompleteModule,
        BreadcrumbModule,
        ButtonModule,
        CalendarModule,
        CarouselModule,
        ChartModule,
        CheckboxModule,
        CodeHighlighterModule,
        SharedModule,
        ContextMenuModule,
        DataGridModule,
        DataListModule,
        DataScrollerModule,
        DataTableModule,
        DialogModule,
        DragDropModule,
        DropdownModule,
        EditorModule,
        FieldsetModule,
        GalleriaModule,
        GMapModule,
        GrowlModule,
        InputMaskModule,
        InputSwitchModule,
        InputTextModule,
        InputTextareaModule,
        LightboxModule,
        ListboxModule,
        MegaMenuModule,
        MenuModule,
        MenubarModule,
        MessagesModule,
        MultiSelectModule,
        OrderListModule,
        OverlayPanelModule,
        PaginatorModule,
        PanelModule,
        PanelMenuModule,
        PasswordModule,
        PickListModule,
        ProgressBarModule,
        RadioButtonModule,
        RatingModule,
        ScheduleModule,
        SelectButtonModule,
        SlideMenuModule,
        SliderModule,
        SpinnerModule,
        SplitButtonModule,
        TabMenuModule,
        TabViewModule,
        TerminalModule,
        TieredMenuModule,
        ToggleButtonModule,
        ToolbarModule,
        TooltipModule,
        TreeModule,
        TreeTableModule
    ],
    declarations: [
        MainComponent,
        AppComponent,
        CodeMirrorComponent,
        FileManagerComponent,
        DescriptionComponent,
        TagsComponent,
        NavBarComponent,
        TerminalComponent
    ],
    providers: [
        routingProviders,
        TagService,
        JavalabService
    ],
    bootstrap: [MainComponent]
})
export class MainModule {

}